### ISSUE TITLE
Import relocation does not refer to code segment

### ISSUE THREAD

**Issue by star-tek-mb** [fedor4ever/elf2e32#11]
Hi. Can you help me pointing out, is that a elf2e32 problem or my problem.
I have my [mbedtls test project](https://github.com/star-tek-mb/mbedtls-symbian-test). And i cannot build e32 image because of that annoying problem:

```elf2e32 : Error: E1065: 'memset' : 'hello' Import relocation does not refer to code segment.```

What can you suggest?

**Comment by fedor4ever** [comment]
Well, position independent binaries doesn't support by symbian. Elf2e32 can't check for that. elf2e32_next detect that and treat as error

**Comment by star-tek-mb** [comment]
Ive expected that, but I checked my makefile for PIC or PIE. I got GCCE 5.5.0 toolchain from your build script. How to know whether my binary compiled with position independent code enabled? Does GCC 5.5.0 turns on -fPIC or -fPIE by default?

**Comment by star-tek-mb** [comment]
I found it. I was compiling my binaries with pie:
```hello: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, not stripped```

I have to pass -no-pie to linker option. But now I stuck at this errors:
```
arm-none-symbianelf-ld: attempted static link of dynamic object libstdcpp.dso
arm-none-symbianelf-ld: attempted static link of dynamic object libc.dso
arm-none-symbianelf-ld: attempted static link of dynamic object dfpaeabi.dso
arm-none-symbianelf-ld: attempted static link of dynamic object dfprvct2_2.dso
arm-none-symbianelf-ld: attempted static link of dynamic object drtaeabi.dso
arm-none-symbianelf-ld: attempted static link of dynamic object scppnwdl.dso
arm-none-symbianelf-ld: attempted static link of dynamic object drtrvct2_2.dso
```

**Comment by fedor4ever** [comment]
I'm not familiar with cmake. I recommend to find where that option comes and disable it.
P.S. why you use cmake? abld build system works fine.

**Comment by star-tek-mb** [comment]
Ok, thanks. Thats my problem, then. I need to test on abld that mbedtls test project. CMake makes porting several libs much easier, also its much more modern than abld.

**Comment by star-tek-mb** [comment]
I checked executables compiled with default s60 sdk 3rd edition installation (with gcc 3). And projects built by abld also produces PIE executable. How is it working btw?

**Comment by fedor4ever** [comment]
> I checked executables compiled with default s60 sdk 3rd edition installation (with gcc 3). And projects built by abld also produces PIE executable. How is it working btw?

Hell if I know. That tool code bloated and hard to fix. I give up and began write from scratch. Give me raw elf to see.
I try -fpic myself and crash elf2e32. Can you run that file on phone?

**Comment by fedor4ever** [comment]
> CMake makes porting several libs much easier, also its much more modern than abld.

But you loose on-device debugging with coda. And carbide integration too.

**Comment by star-tek-mb** [comment]
Yep. I have raw elf file with map file.
[hello.zip](https://github.com/fedor4ever/elf2e32/files/4608793/hello.zip)
To build ELF executable abld passes "-shared" option. Thats combined with -no-pie breaks dynamic linking. Actually, I dont need mbedtls project on symbian os. I took it just for testing process. Other code of mine works fine btw.
Thank you, in advance.

P.S coda is not working for s60v3 (i think). Im testing my applications manually: Copy over USB, delete old app, install new app, test. This is so time-consuming. I need look forward to TRK at least.
